version: '4.12'
services:
  php-apache-environment:
    container_name: oohq3e
    build: php
    volumes:
      - type: bind
        source: ./src
        target: /var/www/html
    ports:
      - "80:80"
  db:
    container_name: db
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: MYSQL_PASSWD
      MYSQL_DATABASE: oohq3e
      MYSQL_USER: MYSQL_USER
      MYSQL_PASSWORD: MYSQL_PASSWORD
    ports:
      - "3306:3306"